### ISSUE TITLE
required .net framework 4.5

### ISSUE THREAD

**Issue by sunmeplz** [mmtrt/cncra2yr#14]
If you click update, game starts asking .net 4.5

is it possible to include .net 4.5 to original image(4.0 is used at the moment)?

**Comment by mmtrt** [comment]
does game still works with 4.0 or is it really requires 4.5 to work?

**Comment by sunmeplz** [comment]
after update no, may be there is another way to update cncnet to 5.5?

**Comment by mmtrt** [comment]
fixed the issue though after update download relaunching game does update it despite of error.

**Comment by sunmeplz** [comment]
in my case the error below
Unhandled Exception: System.NotSupportedException: XNA Framework Reach profile supports a maximum Texture2D size of 2048.
   at Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException(String message, Object arg1, Object arg2)
   at Microsoft.Xna.Framework.Graphics.Texture2D.ValidateCreationParameters(ProfileCapabilities profile, Int32 width, Int32 height, SurfaceFormat format, Boolean mipMap)
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D.CreateRenderTarget(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipMap, SurfaceFormat preferredFormat, DepthFormat preferredDepthFormat, Int32 preferredMultiSampleCount, RenderTargetUsage usage)
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipMap, SurfaceFormat preferredFormat, DepthFormat preferredDepthFormat, Int32 preferredMultiSampleCount, RenderTargetUsage usage)
   at Rampastring.XNAUI.WindowManager.RecalculateScaling()
   at Rampastring.XNAUI.WindowManager.SetRenderResolution(Int32 x, Int32 y)
   at DTAClient.DXGUI.GameClass.SetGraphicsMode(WindowManager wm)
   at DTAClient.DXGUI.GameClass.Initialize()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at DTAClient.Startup.Execute()
   at DTAClient.PreStartup.Initialize(StartupParams parameters)
   at DTAClient.Program.Main(String[] args)
wine: Unhandled exception 0xe0434352 in thread 44 at address 0x320023:0x7b43c92c (thread 0044), starting debugger...
Can't attach process 0043: error 5


Anyway thanks for your work and help^)
heve a nice day

**Comment by mmtrt** [comment]
try with lower resolution see if it works.
