### ISSUE TITLE
Can not create a LAN game

### ISSUE THREAD

**Issue by Razrael** [mmtrt/cncra2yr#17]
When trying to start a game in the LAN lobby, I just get an error when clicking on "New Game" and the game crashes.

```Unhandled Exception: System.Net.Sockets.SocketException: Connection refused 127.0.0.1:1233
   at System.Net.Sockets.TcpClient.Connect(String hostname, Int32 port)
   at DTAClient.DXGUI.Multiplayer.GameLobby.LANGameLobby.SetUp(Boolean isHost, IPEndPoint hostEndPoint, TcpClient client)
   at DTAClient.DXGUI.Multiplayer.LANLobby.GameCreationWindow_NewGame(Object sender, EventArgs e)
   at DTAClient.DXGUI.Multiplayer.LANGameCreationWindow.BtnNewGame_LeftClick(Object sender, EventArgs e)
   at Rampastring.XNAUI.XNAControls.XNAControl.OnLeftClick()
   at Rampastring.XNAUI.XNAControls.XNAButton.OnLeftClick()
   at Rampastring.XNAUI.XNAControls.XNAControl.Update(GameTime gameTime)
   at Rampastring.XNAUI.XNAControls.XNAButton.Update(GameTime gameTime)
   at Rampastring.XNAUI.XNAControls.XNAControl.Update(GameTime gameTime)
   at Rampastring.XNAUI.XNAControls.XNAPanel.Update(GameTime gameTime)
   at Rampastring.XNAUI.XNAControls.XNAControl.Update(GameTime gameTime)
   at Rampastring.XNAUI.XNAControls.XNAPanel.Update(GameTime gameTime)
   at ClientGUI.DarkeningPanel.Update(GameTime gameTime)
   at Rampastring.XNAUI.XNAControls.XNAControl.Update(GameTime gameTime)
   at Rampastring.XNAUI.XNAControls.XNAPanel.Update(GameTime gameTime)
   at DTAClient.DXGUI.Multiplayer.LANLobby.Update(GameTime gameTime)
   at Rampastring.XNAUI.XNAControls.XNAControl.Update(GameTime gameTime)
   at Rampastring.XNAUI.XNAControls.XNAPanel.Update(GameTime gameTime)
   at ClientGUI.DarkeningPanel.Update(GameTime gameTime)
   at Rampastring.XNAUI.WindowManager.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at DTAClient.Startup.Execute()
   at DTAClient.PreStartup.Initialize(StartupParams parameters)
   at DTAClient.Program.Main(String[] args)
wine: Unhandled exception 0xe0434352 in thread 9 at address 0x320023:0x7b43c92c (thread 0009), starting debugger...
Can't attach process 0008: error 5
```

![image](https://user-images.githubusercontent.com/8451816/78059739-adfde480-738a-11ea-8d0c-68537d670d79.png)

![image](https://user-images.githubusercontent.com/8451816/78059823-d5ed4800-738a-11ea-92a4-a16b13fe861d.png)

There is something listening on port 1233 while the game runs:
```netstat -tulpn | grep 1233
tcp        0      0 0.0.0.0:1233            0.0.0.0:*               LISTEN      3694698/clientxna.e
```

I am running Arch Linux. Creating a game in the online lobby works fine.
I hope someone has an idea on how to fix this.

**Comment by mmtrt** [comment]
This feature is not working in `WINE` so you have to use online lobby unfortunately.

**Comment by Razrael** [comment]
Ah thank you.
Is it specific to this snap or in general?
Is there a bug report about it somewhere, so I could follow it?

**Comment by mmtrt** [comment]
I tried it on local wine setup which crashed similarly to snap.

maybe post about it here
 https://github.com/CnCNet/cncnet-yr-client-package/issues

or here

https://bugs.winehq.org/

**Comment by recolic** [comment]
I have a same issue on Manjaro linux:

```
wine: Call from 0x7b43c92c to unimplemented function usp10.dll.ScriptBreak, aborting

Unhandled Exception: System.Net.Sockets.SocketException: Unknown error (0x2740)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at DTAClient.DXGUI.Multiplayer.GameLobby.LANGameLobby.ListenForClients()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
wine: Unhandled exception 0xe0434352 in thread 78 at address 0x11480023:0x7b43c92c (thread 0078), starting debugger...
/snap/cncra2yr/43/bin/sommelier: line 163: 20739 Killed                  env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" taskset -c 0 "${WINELOADER}" "${WINE_EXE}"
```

I can remember that LAN gaming was working several days ago.

**Comment by mmtrt** [comment]
LAN is fixed by upstream changes in client.

**Comment by b3tts32** [comment]
I'm running into this same issue on a ubuntu 20.04 install. Do you know what was fixed upstream?

**Comment by mmtrt** [comment]
it should be working now on latest snap update
