### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by lazydays79** [mmtrt/cncra2yr#23]
Today I installed ccra2yr and it run fine. After quitting the game, I'm not able to launch it any more.

OS is pop os 20.10, everything is up to date.

` michael@marvin $ snap run cncra2yr

Unhandled Exception: System.NotSupportedException: XNA Framework Reach profile supports a maximum Texture2D size of 2048.
   at Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException(String message, Object arg1, Object arg2)
   at Microsoft.Xna.Framework.Graphics.Texture2D.ValidateCreationParameters(ProfileCapabilities profile, Int32 width, Int32 height, SurfaceFormat format, Boolean mipMap)
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D.CreateRenderTarget(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipMap, SurfaceFormat preferredFormat, DepthFormat preferredDepthFormat, Int32 preferredMultiSampleCount, RenderTargetUsage usage)
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipMap, SurfaceFormat preferredFormat, DepthFormat preferredDepthFormat, Int32 preferredMultiSampleCount, RenderTargetUsage usage)
   at Rampastring.XNAUI.WindowManager.RecalculateScaling()
   at Rampastring.XNAUI.WindowManager.SetRenderResolution(Int32 x, Int32 y)
   at DTAClient.DXGUI.GameClass.SetGraphicsMode(WindowManager wm)
   at DTAClient.DXGUI.GameClass.Initialize()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at DTAClient.Startup.Execute()
   at DTAClient.PreStartup.Initialize(StartupParams parameters)
   at DTAClient.Program.Main(String[] args)
wine: Unhandled exception 0xe0434352 in thread 9 at address 0x390023:0x7b43c92c (thread 0009), starting debugger...
Can't attach process 0008: error 5`

**Comment by mmtrt** [comment]
lower screen resolution try again and set both resolutions to 1080 from launcher.

**Comment by Nippyfus** [comment]
Indeed, I have the same issue that lazydays, but we can't have access to the launcher, the game just crashes and Says:
![Screenshot from 2021-07-11 10-40-36](https://user-images.githubusercontent.com/76571984/125188545-78ee6c00-e234-11eb-8ab3-0e60712f2bd9.png)

**Comment by mmtrt** [comment]
@Nippyfus try `opengl` or `directx`

`snap run cncra2yr.cncra2yrogl`

`snap run cncra2yr.cncra2yrdx`

**Comment by Nippyfus** [comment]
So I found the problem by watching logs. The system resolution is too high for cncra2yr, change your system resolution and the problem is solved. Indeed, XNA only supports a lower resolution than 2000px and my resolution was 3200x1800.
Thanks for your help

**Comment by JonasGroeger** [comment]
Had the same issue. Changed the resolution of my Laptop and inside the CnCNet Client to 1920x1080. It worked flawlessly then.
