### ISSUE TITLE
FileNotFoundException: Could not find file 'C:\Westwood\RA2\Resources\Binaries\XNA\Localization.dll'

### ISSUE THREAD

**Issue by JonasGroeger** [mmtrt/cncra2yr#28]
After patching to the latest version (8.11.0), this fails with the error in the title. Before, everything worked. Is this an issue with the snap or an upstream issue?

```
snap run cncra2yr # Runs /snap/bin/cncra2yr.cncra2yrogl
Starting application..

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Localization, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. File not found. ---> System.IO.FileNotFoundException: Could not find file 'C:\Westwood\RA2\Resources\Binaries\XNA\Localization.dll'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at DTAClient.Program.CurrentDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   --- End of inner exception stack trace ---
   at DTAClient.Program.Main(String[] args)
wine: Unhandled exception 0xe0434352 in thread 3ce at address 0x330023:0x7b43c92c (thread 03ce), starting debugger...
Can't attach process 03cd: error 5

**Comment by edos4** [comment]
Up. Happens on mine too.

**Comment by mmtrt** [comment]
Thanks @xartyx

I've reported this to upstream and they seem to have committed changes.

It should be fixed in upcoming client patch but could require manual change of adding dll if users have broken client v8.11 .

**Comment by JonasGroeger** [comment]
See https://github.com/CnCNet/cncnet-yr-client-package/releases/tag/yr-8.11.1

**Comment by mmtrt** [comment]
Yeah it is fixed just tested fresh install then updated client seem to work fine now.

**Comment by JonasGroeger** [comment]
The update failed for me but I fixed it with:

```
$ pwd
~/snap/cncra2yr/common/.wine/drive_c/Westwood/RA2

$ cp -r Updater/Resources .

**Comment by mmtrt** [comment]
I'm adding a check in snap for broken client users.

**Comment by mmtrt** [comment]
Released snap update should fix broken client.
