### ISSUE TITLE
Failed to create graphics device

### ISSUE THREAD

**Issue by edos4** [mmtrt/cncra2yr#31]
```
13.03. 12:47:13.295    ***Logfile for Yuri's Revenge client***
13.03. 12:47:13.327    Client version: 2.6.11.1
13.03. 12:47:13.327    Loading settings.
13.03. 12:47:13.385    Failed to load the translation file. Could not find file 'C:\Westwood\RA2\Resources\Translation.ini'.
13.03. 12:47:13.431    Initializing updater.
13.03. 12:47:13.434    Update mirror count: 1
13.03. 12:47:13.434    Running from: clientdx.exe
13.03. 12:47:13.436    Operating system: Microsoft Windows NT 5.2.3790 Service Pack 2
13.03. 12:47:13.437    Selected OS profile: WINXP
13.03. 12:47:13.437    Current culture: en-PH
13.03. 12:47:13.450    Removing partial custom component downloads.
13.03. 12:47:13.451    Checking for the existence of FinalSun.ini.
13.03. 12:47:13.451    FinalSun.ini doesn't exist - writing default settings.
13.03. 12:47:13.455    An exception occured while checking the existence of FinalSun settings
13.03. 12:47:13.456    Writing installation path to the Windows registry.
13.03. 12:47:13.466    Starting background processing of INI files.
13.03. 12:47:13.466    /INI/Base does not exist, skipping background processing of INI files.
13.03. 12:47:13.731    Hardware info: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (0 cores) Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (0 cores) Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (0 cores) Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (0 cores) Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (0 cores) Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (0 cores) Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (0 cores) Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (0 cores) Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (0 cores) Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (0 cores) Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (0 cores) Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (0 cores) | Video controller: NVIDIA GeForce GTX 470 | Total physical memory: 23GB
13.03. 12:47:13.806    KABOOOOOOM!!! Info:
13.03. 12:47:13.806    Message: Failed to create graphics device!
13.03. 12:47:13.809    Source: MonoGame.Framework
13.03. 12:47:13.809    TargetSite.Name: CreateDevice
13.03. 12:47:13.811    Stacktrace:    at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice()
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.CreateDevice()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at DTAClient.Startup.Execute()
   at DTAClient.PreStartup.Initialize(StartupParams parameters)
   at DTAClient.Program.Main(String[] args)
13.03. 12:47:13.812    InnerException info:
13.03. 12:47:13.812    Message: HRESULT: [0x80004001], Module: [General], ApiCode: [E_NOTIMPL/Not implemented], Message: Unknown
13.03. 12:47:13.812    Stacktrace:    at SharpDX.Result.CheckError()
   at SharpDX.DXGI.Device1.SetMaximumFrameLatency(Int32 maxLatency)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.CreateSizeDependentResources()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Initialize()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice(GraphicsDeviceInformation gdi)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice()
```

**Comment by mmtrt** [comment]
Is this `clientdx` if so then its known broken.

**Comment by WoMax** [comment]
The same issue. Is there some workaround?

**Comment by mmtrt** [comment]
Try `snap run cncra2yr.cncra2yrogl` see if that helps.

**Comment by WoMax** [comment]
> Try `snap run cncra2yr.cncra2yrogl` see if that helps.

It runs multiplayer, it there some approach to run original game?
