### ISSUE TITLE
Can't run campaigns on Ubuntu 22.04 lts

### ISSUE THREAD

**Issue by ankush-phulia** [mmtrt/cncra2yr#37]
The client and skirmish load and run successfully. I am able to browse the CnCnet games as well.
When trying to start campaigns (RA2 or YR), the game crashed with the following error `File not found`
```
$snap run cncra2yr.cncra2yrogl --debug-log
Starting application..
Running hook '/snap/cncra2yr/93/sommelier/hooks/pre-start'

Unhandled Exception: System.ComponentModel.Win32Exception: File not found
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at ClientGUI.XNALinkButton.OnLeftClick()
   at Rampastring.XNAUI.XNAControls.XNAControl.Update(GameTime gameTime)
   at Rampastring.XNAUI.XNAControls.XNAButton.Update(GameTime gameTime)
   at Rampastring.XNAUI.XNAControls.XNAControl.Update(GameTime gameTime)
   at Rampastring.XNAUI.XNAControls.XNAPanel.Update(GameTime gameTime)
   at Rampastring.XNAUI.XNAControls.XNAControl.Update(GameTime gameTime)
   at Rampastring.XNAUI.XNAControls.XNAPanel.Update(GameTime gameTime)
   at DTAClient.DXGUI.Generic.MainMenuDarkeningPanel.Update(GameTime gameTime)
   at Rampastring.XNAUI.XNAControls.XNAControl.Update(GameTime gameTime)
   at Rampastring.XNAUI.XNAControls.XNAPanel.Update(GameTime gameTime)
   at Rampastring.XNAUI.WindowManager.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.SortingFilteringCollection`1.ForEachFilteredItem[TUserData](Action`2 action, TUserData userData)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at DTAClient.Startup.Execute()
   at DTAClient.PreStartup.Initialize(StartupParams parameters)
   at DTAClient.Program.Main(String[] args)
wine: Unhandled exception 0xe0434352 in thread 1d0 at address 000000007B01192E (thread 01d0), starting debugger...
```
Changing the resolution or the renderer doesn't help, the file not found error persists, but the trace changes a bit

**Comment by mmtrt** [comment]
That feature is broken generally in client so it is expected to not work.

**Comment by ankush-phulia** [comment]
Got it, thanks for the response

**Comment by zimsneexh** [comment]
I assume this is because of the missing movie files in some (free-to-download) versions of the game.

**Comment by zimsneexh** [comment]
The cncnet client does support Campaigns as of [8.26](https://github.com/CnCNet/cncnet-yr-client-package/releases/tag/yr-8.26), so this might be fixable here as well?
